// apps/angular/src/app/app.component.ts
import { JsonPipe } from "@angular/common";
import { Component, signal } from "@angular/core";
import {
  type FormField,
  HlmAlertDescriptionDirective,
  HlmAlertDirective,
  HlmAlertTitleDirective,
  HlmBadgeDirective,
  HlmButtonDirective,
  HlmCardContentDirective,
  HlmCardDescriptionDirective,
  HlmCardDirective,
  HlmCardFooterDirective,
  HlmCardHeaderDirective,
  HlmCardTitleDirective,
  HlmCurrencyInputComponent,
  HlmFormBuilderComponent,
  HlmLabelDirective,
  HlmNumberFieldComponent,
  HlmProgressComponent,
  HlmRatingComponent,
  HlmSeparatorDirective,
  HlmStatCardComponent,
  HlmStatusBadgeComponent,
  HlmStepperComponent,
  HlmTabsComponent,
  HlmTabsContentDirective,
  HlmTabsListDirective,
  HlmTabsTriggerDirective,
  HlmTimelineDirective,
  HlmTimelineItemComponent,
} from "@zied-snoussi/angular";

/**
 * Angular demo for the Bysur Suite — powered by @zied-snoussi/angular (spartan),
 * the Angular counterpart of @zied-snoussi/react (shadcn). One design language,
 * two frameworks. No Stencil, no web components — native Angular.
 */
@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    JsonPipe,
    HlmButtonDirective,
    HlmBadgeDirective,
    HlmStatusBadgeComponent,
    HlmStatCardComponent,
    HlmAlertDirective,
    HlmAlertTitleDirective,
    HlmAlertDescriptionDirective,
    HlmCardDirective,
    HlmCardHeaderDirective,
    HlmCardTitleDirective,
    HlmCardDescriptionDirective,
    HlmCardContentDirective,
    HlmCardFooterDirective,
    HlmSeparatorDirective,
    HlmProgressComponent,
    HlmStepperComponent,
    HlmTimelineDirective,
    HlmTimelineItemComponent,
    HlmTabsComponent,
    HlmTabsListDirective,
    HlmTabsTriggerDirective,
    HlmTabsContentDirective,
    HlmLabelDirective,
    HlmNumberFieldComponent,
    HlmCurrencyInputComponent,
    HlmRatingComponent,
    HlmFormBuilderComponent,
  ],
  template: `
    <main class="mx-auto max-w-5xl px-4 py-8">
      <header class="flex items-start justify-between gap-4">
        <div>
          <h1 class="font-semibold text-2xl tracking-tight">Bysur Suite — Angular</h1>
          <p class="mt-1.5 text-sm text-muted-foreground">
            Powered by <code>&#64;zied-snoussi/angular</code> (spartan) — the Angular
            twin of the React/shadcn package. Native Angular, no web components.
          </p>
        </div>
        <button hlmBtn variant="outline" (click)="toggleTheme()">
          {{ dark() ? '☀ Light' : '☾ Dark' }} theme
        </button>
      </header>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">StatCard</h2>
        <div class="mt-4 grid gap-4 sm:grid-cols-3">
          <hlm-stat-card label="Active policies" value="1,284" delta="+12.5%" trend="up" hint="vs last month" />
          <hlm-stat-card label="Open claims" value="47" delta="-3.1%" trend="down" hint="vs last month" />
          <hlm-stat-card label="Renewal rate" value="92.4%" delta="+0.8pt" trend="up" hint="quarter to date" />
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">StatusBadge &amp; Badge</h2>
        <div class="mt-4 flex flex-wrap items-center gap-2">
          @for (s of statuses; track s) {
            <hlm-status-badge [status]="s" />
          }
          <hlm-status-badge status="vip" label="VIP client" tone="info" />
        </div>
        <div class="mt-3 flex flex-wrap items-center gap-2">
          <span hlmBadge>Default</span>
          <span hlmBadge variant="secondary">Auto</span>
          <span hlmBadge variant="destructive">Overdue</span>
          <span hlmBadge variant="outline">Outline</span>
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">Button</h2>
        <div class="mt-4 flex flex-wrap items-center gap-3">
          <button hlmBtn>Default</button>
          <button hlmBtn variant="secondary">Secondary</button>
          <button hlmBtn variant="destructive">Destructive</button>
          <button hlmBtn variant="outline">Outline</button>
          <button hlmBtn variant="ghost">Ghost</button>
          <button hlmBtn variant="link">Link</button>
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">Alert</h2>
        <div class="mt-4 flex max-w-xl flex-col gap-3">
          <div hlmAlert variant="success">
            <h5 hlmAlertTitle>Payment received</h5>
            <div hlmAlertDescription>Premium paid for the 2026 term.</div>
          </div>
          <div hlmAlert variant="warning">
            <h5 hlmAlertTitle>Renewal due</h5>
            <div hlmAlertDescription>This policy expires in 14 days.</div>
          </div>
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">Card, Separator, Progress</h2>
        <div hlmCard class="mt-4 max-w-xl">
          <div hlmCardHeader>
            <h3 hlmCardTitle>Policy BYS-2026-004821</h3>
            <p hlmCardDescription>Auto — Comprehensive</p>
          </div>
          <div hlmCardContent>
            <div class="flex items-center justify-between">
              <span class="font-medium text-sm">Zied Snoussi</span>
              <hlm-status-badge status="active" />
            </div>
            <div hlmSeparator class="my-4"></div>
            <div class="flex flex-col gap-3">
              <hlm-progress label="Deductible met" tone="success" [value]="100" />
              <hlm-progress label="Annual coverage used" tone="warning" [value]="72" />
              <hlm-progress label="Claim limit reached" tone="danger" [value]="95" />
            </div>
          </div>
          <div hlmCardFooter>
            <button hlmBtn>Renew policy</button>
          </div>
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">Stepper</h2>
        <div class="mt-4 max-w-2xl">
          <hlm-stepper [current]="2" [steps]="steps" />
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">Timeline</h2>
        <div hlmTimeline class="mt-4 max-w-md pl-2">
          <hlm-timeline-item time="Today, 09:12" title="Claim approved">
            Payout of $3,400 scheduled to the policyholder.
          </hlm-timeline-item>
          <hlm-timeline-item time="Yesterday" title="Adjuster review completed">
            Damage assessed as within coverage limits.
          </hlm-timeline-item>
          <hlm-timeline-item time="Mar 1" title="Claim submitted" />
        </div>
      </section>

      <section class="mt-10">
        <h2 class="font-semibold text-sm">Interactive</h2>
        <hlm-tabs value="controls" class="mt-4 max-w-[460px]">
          <div hlmTabsList>
            <button hlmTabsTrigger value="controls">Controls</button>
            <button hlmTabsTrigger value="quote">Quote form</button>
          </div>
          <div hlmTabsContent value="controls">
            <div class="flex flex-col gap-6">
              <div>
                <label hlmLabel>Number of dependents</label>
                <div class="mt-1.5">
                  <hlm-number-field [value]="dependents()" (valueChange)="dependents.set($event)" [min]="0" [max]="12" aria-label="Dependents" />
                </div>
                <p class="mt-1.5 text-muted-foreground text-xs">Selected: {{ dependents() }}</p>
              </div>
              <div class="max-w-[260px]">
                <label hlmLabel>Coverage amount</label>
                <div class="mt-1.5">
                  <hlm-currency-input [value]="coverage()" (valueChange)="coverage.set($event)" currency="USD" locale="en-US" aria-label="Coverage amount" />
                </div>
                <p class="mt-1.5 text-muted-foreground text-xs">Value: {{ coverage() ?? '—' }}</p>
              </div>
              <div>
                <label hlmLabel>How was your last claim experience?</label>
                <div class="mt-1.5">
                  <hlm-rating [value]="csat()" (valueChange)="csat.set($event)" aria-label="CSAT" />
                </div>
                <p class="mt-1.5 text-muted-foreground text-xs">{{ csat() }} / 5</p>
              </div>
            </div>
          </div>
          <div hlmTabsContent value="quote">
            <div class="max-w-[460px]">
              <hlm-form-builder [fields]="quoteFields" submitLabel="Request quote" (submitted)="submitted.set($event)" />
              @if (submitted()) {
                <pre class="mt-4 overflow-x-auto rounded-lg bg-muted p-3 text-xs">{{ submitted() | json }}</pre>
              }
            </div>
          </div>
        </hlm-tabs>
      </section>

      <footer class="mt-16 border-t pt-6 text-xs text-muted-foreground">
        One design language, two frameworks — <code>&#64;zied-snoussi/react</code>
        (shadcn) and <code>&#64;zied-snoussi/angular</code> (spartan).
      </footer>
    </main>
  `,
})
export class AppComponent {
  readonly statuses = [
    "active",
    "pending",
    "in-review",
    "quoted",
    "bound",
    "lapsed",
    "cancelled",
    "overdue",
    "rejected",
    "draft",
    "new",
  ];

  readonly steps = [
    { label: "Quote", description: "Coverage & price" },
    { label: "Details", description: "Applicant info" },
    { label: "Review", description: "Confirm terms" },
    { label: "Bind", description: "Issue policy" },
  ];

  readonly quoteFields: FormField[] = [
    { name: "fullName", label: "Full name", type: "text", required: true },
    {
      name: "email",
      label: "Email",
      type: "email",
      required: true,
      description: "We'll send the quote here.",
    },
    {
      name: "product",
      label: "Product",
      type: "select",
      required: true,
      placeholder: "Choose a product",
      options: [
        { label: "Auto — Comprehensive", value: "auto" },
        { label: "Home — Buildings & contents", value: "home" },
        { label: "Travel — Annual multi-trip", value: "travel" },
      ],
    },
    { name: "newsletter", label: "Email me renewal reminders", type: "switch" },
    {
      name: "terms",
      label: "I accept the terms and conditions",
      type: "checkbox",
      required: true,
    },
  ];

  readonly dark = signal(false);
  readonly dependents = signal(2);
  readonly coverage = signal<number | undefined>(50_000);
  readonly csat = signal(4);
  readonly submitted = signal<Record<string, string | boolean> | null>(null);

  toggleTheme(): void {
    const next = !this.dark();
    this.dark.set(next);
    document.documentElement.classList.toggle("dark", next);
  }
}

// apps/react-vite/src/App.tsx
/**
 * React + Vite demo — the SAME @zied-snoussi/react package as the Next.js app,
 * in a plain client-rendered React app with no framework magic.
 *
 * Everything is a normal component here (no RSC), so the interactive and
 * presentational components sit side by side in one file.
 */

import {
  Alert,
  AlertDescription,
  AlertTitle,
  Avatar,
  AvatarFallback,
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Checkbox,
  CurrencyInput,
  DescriptionItem,
  DescriptionList,
  EmptyState,
  FormBuilder,
  type FormField,
  Input,
  Label,
  NumberField,
  Progress,
  RadioGroup,
  RadioGroupItem,
  Rating,
  Separator,
  Skeleton,
  Spinner,
  StatCard,
  StatusBadge,
  Stepper,
  Switch,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  Textarea,
  Timeline,
  TimelineItem,
} from "@zied-snoussi/react";
import { useState } from "react";

const quoteFields: FormField[] = [
  { name: "fullName", label: "Full name", type: "text", required: true },
  {
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    description: "We'll send the quote here.",
  },
  {
    name: "product",
    label: "Product",
    type: "select",
    required: true,
    placeholder: "Choose a product",
    options: [
      { label: "Auto — Comprehensive", value: "auto" },
      { label: "Home — Buildings & contents", value: "home" },
    ],
  },
  { name: "notes", label: "Notes", type: "textarea" },
  { name: "terms", label: "I accept the terms", type: "checkbox", required: true },
];

export function App() {
  const [dark, setDark] = useState(false);
  const [dependents, setDependents] = useState(2);
  const [coverage, setCoverage] = useState<number | undefined>(50_000);
  const [csat, setCsat] = useState(4);
  const [submitted, setSubmitted] = useState<Record<
    string,
    string | boolean
  > | null>(null);

  const toggleTheme = () => {
    const next = !dark;
    setDark(next);
    document.documentElement.classList.toggle("dark", next);
  };

  return (
    <main className="page">
      <header
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          gap: 16,
        }}
      >
        <div>
          <h1 style={{ margin: 0, fontSize: "1.6rem", letterSpacing: "-0.02em" }}>
            Bysur Suite — React + Vite
          </h1>
          <p style={{ margin: "6px 0 0", color: "var(--color-muted-foreground)" }}>
            The same <code>@zied-snoussi/react</code> package, plain React (no SSR).
          </p>
        </div>
        <Button onClick={toggleTheme} variant="outline">
          {dark ? "☀ Light" : "☾ Dark"} theme
        </Button>
      </header>

      <section className="section">
        <h2>KPIs</h2>
        <div className="grid-3">
          <StatCard delta="+12.5%" hint="vs last month" label="Active policies" trend="up" value="1,284" />
          <StatCard delta="-3.1%" hint="vs last month" label="Open claims" trend="down" value="47" />
          <StatCard delta="+0.8pt" hint="QTD" label="Renewal rate" trend="up" value="92.4%" />
        </div>
      </section>

      <section className="section">
        <h2>Statuses &amp; badges</h2>
        <div className="row">
          {["active", "pending", "in-review", "lapsed", "overdue", "quoted", "draft", "new"].map(
            (s) => (
              <StatusBadge key={s} status={s} />
            )
          )}
          <Badge variant="secondary">Auto</Badge>
          <Badge variant="destructive">Overdue</Badge>
        </div>
      </section>

      <section className="section">
        <h2>Buttons</h2>
        <div className="row">
          <Button>Default</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="destructive">Destructive</Button>
          <Button variant="outline">Outline</Button>
          <Button variant="ghost">Ghost</Button>
          <Button variant="link">Link</Button>
          <Button disabled>Disabled</Button>
        </div>
      </section>

      <section className="section">
        <h2>Alerts</h2>
        <div className="stack" style={{ maxWidth: 520 }}>
          <Alert variant="success">
            <AlertTitle>Payment received</AlertTitle>
            <AlertDescription>Premium paid for the 2026 term.</AlertDescription>
          </Alert>
          <Alert variant="warning">
            <AlertTitle>Renewal due</AlertTitle>
            <AlertDescription>This policy expires in 14 days.</AlertDescription>
          </Alert>
          <Alert variant="destructive">
            <AlertTitle>Policy lapsed</AlertTitle>
            <AlertDescription>Coverage ended on 12 June 2026.</AlertDescription>
          </Alert>
        </div>
      </section>

      <section className="section">
        <h2>Policy card</h2>
        <Card style={{ maxWidth: 520 }}>
          <CardHeader>
            <CardTitle>Policy BYS-2026-004821</CardTitle>
            <CardDescription>Auto — Comprehensive</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="row" style={{ marginBottom: 12 }}>
              <Avatar>
                <AvatarFallback>ZS</AvatarFallback>
              </Avatar>
              <span style={{ fontSize: 14, fontWeight: 500 }}>Zied Snoussi</span>
            </div>
            <Separator style={{ margin: "12px 0" }} />
            <DescriptionList>
              <DescriptionItem term="Premium">$1,240 / year</DescriptionItem>
              <DescriptionItem term="Deductible">$500</DescriptionItem>
              <DescriptionItem term="Status">
                <StatusBadge status="active" />
              </DescriptionItem>
            </DescriptionList>
            <Separator style={{ margin: "12px 0" }} />
            <div className="stack">
              <Progress label="Deductible met" tone="success" value={100} />
              <Progress label="Coverage used" tone="warning" value={72} />
              <Progress label="Claim limit" tone="danger" value={95} />
            </div>
          </CardContent>
          <CardFooter>
            <Button>Renew policy</Button>
          </CardFooter>
        </Card>
      </section>

      <section className="section">
        <h2>Stepper &amp; Timeline</h2>
        <div style={{ maxWidth: 600 }}>
          <Stepper
            current={2}
            steps={[
              { label: "Quote" },
              { label: "Details" },
              { label: "Review" },
              { label: "Bind" },
            ]}
          />
        </div>
        <div style={{ maxWidth: 460, marginTop: 24 }}>
          <Timeline>
            <TimelineItem time="Today" title="Claim approved">
              Payout of $3,400 scheduled.
            </TimelineItem>
            <TimelineItem time="Mar 3" title="Documents uploaded" />
            <TimelineItem time="Mar 1" title="Claim submitted" />
          </Timeline>
        </div>
      </section>

      <section className="section">
        <h2>Form controls</h2>
        <div className="stack" style={{ maxWidth: 400 }}>
          <div>
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="you@bysur.com" type="email" />
          </div>
          <div>
            <Label htmlFor="notes">Notes</Label>
            <Textarea id="notes" placeholder="Tell us more…" />
          </div>
          <div className="row">
            <Checkbox defaultChecked id="terms" />
            <Label htmlFor="terms">Accept terms</Label>
          </div>
          <div className="row">
            <Switch defaultChecked id="notify" />
            <Label htmlFor="notify">Renewal notifications</Label>
          </div>
          <RadioGroup defaultValue="standard" name="plan">
            <RadioGroupItem description="Liability only" label="Basic" value="basic" />
            <RadioGroupItem description="Liability + collision" label="Standard" value="standard" />
            <RadioGroupItem description="Full coverage" label="Premium" value="premium" />
          </RadioGroup>

          <div>
            <Label>Dependents</Label>
            <div style={{ marginTop: 6 }}>
              <NumberField aria-label="Dependents" max={12} min={0} onValueChange={setDependents} value={dependents} />
            </div>
          </div>

          <div>
            <Label>Coverage amount</Label>
            <div style={{ marginTop: 6 }}>
              <CurrencyInput aria-label="Coverage" defaultValue={50_000} onValueChange={setCoverage} />
            </div>
            <small style={{ color: "var(--color-muted-foreground)" }}>Value: {coverage ?? "—"}</small>
          </div>

          <div>
            <Label>Satisfaction</Label>
            <div style={{ marginTop: 6 }}>
              <Rating aria-label="CSAT" onValueChange={setCsat} value={csat} />
            </div>
          </div>
        </div>
      </section>

      <section className="section">
        <h2>Tabs &amp; FormBuilder</h2>
        <Tabs defaultValue="quote">
          <TabsList>
            <TabsTrigger value="quote">Quote form</TabsTrigger>
            <TabsTrigger value="states">Loading &amp; empty</TabsTrigger>
          </TabsList>

          <TabsContent value="quote">
            <div style={{ maxWidth: 440 }}>
              <FormBuilder fields={quoteFields} onSubmit={setSubmitted} submitLabel="Request quote" />
              {submitted ? (
                <pre
                  style={{
                    marginTop: 16,
                    padding: 12,
                    borderRadius: 8,
                    background: "var(--color-muted)",
                    fontSize: 12,
                    overflowX: "auto",
                  }}
                >
                  {JSON.stringify(submitted, null, 2)}
                </pre>
              ) : null}
            </div>
          </TabsContent>

          <TabsContent value="states">
            <div className="grid-3">
              <Card>
                <CardContent style={{ paddingTop: 24 }}>
                  <div className="row">
                    <Skeleton style={{ height: 48, width: 48, borderRadius: 9999 }} />
                    <div className="stack" style={{ flex: 1, gap: 8 }}>
                      <Skeleton style={{ height: 12, width: "80%" }} />
                      <Skeleton style={{ height: 12, width: "60%" }} />
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent
                  style={{
                    paddingTop: 24,
                    display: "flex",
                    gap: 20,
                    justifyContent: "center",
                    alignItems: "center",
                  }}
                >
                  <Spinner size="sm" />
                  <Spinner />
                  <Spinner size="lg" />
                </CardContent>
              </Card>
              <EmptyState
                description="New leads will show up here."
                icon={<span style={{ fontSize: 28 }}>📇</span>}
                title="No leads yet"
              />
            </div>
          </TabsContent>
        </Tabs>
      </section>
    </main>
  );
}
